### ISSUE TITLE
What should be skipped? (Buttons, Disabled elements)

### ISSUE THREAD

**Issue by EmarJ** [roman01la/JSONFormData#11]
The [draft](https://darobin.github.io/formic/specs/json/) does not say ~~explicitly~~ which element have to be submitted and which ones have to be skipped.

I think that we could discuss and fill the gaps left by the draft. The main reference in this process could be the "normal" querystring submit procedure.

Currently buttons, that is `<buttons>` and `<input type="button|reset|submit">`, are skipped. The only button submitted with querystring is the one used to submit the form. In JSON case I think this is not necessary.

I propose to skip also elements with attribute `disabled` as happens with querystring forms.

I cannot think other elements that have to be skipped, but maybe others have ideas.

**Comment by roman01la** [comment]
I agree. I think the polyfill should gather data from exactly same element (in combination with attributes like `disabled`) as usual form submitting does. We don't want to mess around with standard behaviour, just to provide an ability to submit JSON, that's it.

**Comment by EmarJ** [comment]
I have submitted a pull request to skip disabled elements

**Comment by roman01la** [comment]
Merged
